# This file was generated by GoReleaser. DO NOT EDIT.
cask "laravisor" do
  name "laravisor"
  desc "TUI for managing Laravel development processes"
  homepage "https://github.com/mikecvermeer/laravisor"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laravisor"

  on_macos do
    on_intel do
      url "https://github.com/mikecvermeer/laravisor/releases/download/v#{version}/laravisor_#{version}_darwin_amd64.tar.gz"
      sha256 "697a09afdc2dce993fcd5afb273d74c48891a7bfa1269d856952384b291b8ca9"
    end
    on_arm do
      url "https://github.com/mikecvermeer/laravisor/releases/download/v#{version}/laravisor_#{version}_darwin_arm64.tar.gz"
      sha256 "29822ec981ad8e2ddf7bdc21e41e00aeb92121a54a88d3891f51ba09e6d1d0f9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mikecvermeer/laravisor/releases/download/v#{version}/laravisor_#{version}_linux_amd64.tar.gz"
      sha256 "bc46e294bc0fab2636e28ff8a29a55d961e5fe5db23f3c9122e22c4c4cf8cf2d"
    end
    on_arm do
      url "https://github.com/mikecvermeer/laravisor/releases/download/v#{version}/laravisor_#{version}_linux_arm64.tar.gz"
      sha256 "1049d04da5e6fd03fc41e8956a99a42ff17e0ff66df14bbc793f578fd89702c6"
    end
  end

  # No zap stanza required
end
